<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('categories')->insert(
            array(
                array(
                    'rayvarz_id' => 1001,
                    'name' => 'مواد معدني',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3003009,
                    'name' => '	لوازم بيل ',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),

                array(
                    'rayvarz_id' => 3004001,
                    'name' => '	تسمه ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3005003,
                    'name' => '	مقاومت ها ،آي سي ها ،ريل، ترمينال ها و خازن ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3016001,
                    'name' => '	قطعات يدکي ابزار دقيق',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3023006,
                    'name' => '	قطعات يدکي لبه زن',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3024001,
                    'name' => '	قطعات يدکي بلوک سبک',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3023007,
                    'name' => '	قطعات يدکي سي ان سي ',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 2004004,
                    'name' => '	لوازم كولر و بخاري و سماور',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 2004005,
                    'name' => '	پوشاك و وسايل ايمني و بهداشتي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 2004006,
                    'name' => '	لوازم امدادي و پزشكي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 2004007,
                    'name' => '	ساير ملزومات عمومي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 2005,
                    'name' => '	مصرفي دستگاه هاي خط توليد بلوک',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 2007,
                    'name' => '	مصرفي دستگاه هاي خط توليد صنايع جانبي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 2008001,
                    'name' => '	اقلام مصرفي بسته بندي محصول شيشه',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 22100,
                    'name' => '	رک',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 2501,
                    'name' => '	مواد مصرفي هبلکس',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 2502,
                    'name' => '	اقلام مصرفي و بسته بندي هبلکس',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3001001,
                    'name' => '	لوله ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3003007,
                    'name' => '	لوازم بلدوزر',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3003001,
                    'name' => '	لوازم تراكتور',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3004010,
                    'name' => '	فيبر و فنر ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3005006,
                    'name' => '	پره ها و هواكش ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3003005,
                    'name' => '	لوازم ليفتراك',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3019001,
                    'name' => '	قطعات يدکي کاتينگ',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3001011,
                    'name' => '	اتصالات سوپرپايپ و رادياتور و آتشنشاني',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3001002,
                    'name' => '	اتصالات گاوانيزه وبرنجي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3001003,
                    'name' => '	شير و فلكه و لوازم شيرآلات',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3001004,
                    'name' => '	فشار سنج ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3001005,
                    'name' => '	اتصالات پلي اتيلن و تفلوني و ريتگ ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3001006,
                    'name' => '	اتصالات بسپار و بست ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3001007,
                    'name' => '	اتصالات پليکا ',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3001008,
                    'name' => '	اتصالات فلنج و لرزگيرها ',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3001009,
                    'name' => '	اتصالات گسگت ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3001010,
                    'name' => '	اتصالات جوشي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3001012,
                    'name' => '	اتصالات استيل ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3002001,
                    'name' => '	سيم ها و كابل ها و لوازم مربوطه',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3002002,
                    'name' => '	كليد و پريز و روشنايي ها و لوازم مربوطه',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3003002,
                    'name' => '	لوازم موتورسيكلت',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3003003,
                    'name' => '	لوازم ماشين سواري',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3003004,
                    'name' => '	لوازم دوچرخه',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3003006,
                    'name' => '	لوازم ماشين هاي سنگين',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3003008,
                    'name' => '	لوازم لودر',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3004002,
                    'name' => '	بلبرينگ ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3004003,
                    'name' => '	كاسه نمد ها و اورينگ ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3004004,
                    'name' => '	ياتاقان ها و گريس خورها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3004005,
                    'name' => '	پيچ ، مهره، واشر و رولپلاك',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3004006,
                    'name' => '	كرپي ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3004007,
                    'name' => '	شيربرقي ها، بوبين ها و اتصالات پنوماتيك',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3004008,
                    'name' => '	روان سازها ،چسب ها و حلال ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3004009,
                    'name' => '	زنجير ها ،چرخ دنده ها و سيم بكسل',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3004011,
                    'name' => '	شفت ها و گايدهاي فلزي و تفلوني',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3004012,
                    'name' => '	تجهيزات برودتي و گرمايشي صنعتي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3004013,
                    'name' => '	الكتروموتورها و لوازم مربوطه',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3004014,
                    'name' => '	خارها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3004015,
                    'name' => '	تجهيزات و ماشين آلات مکانيکي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3005001,
                    'name' => '	فيوز ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3005002,
                    'name' => '	فتوسل ها و سنسور ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3005004,
                    'name' => '	كنتاكتورها،اينورترها، رله ، كليدهاي حرارتي،بي متال ها و لوازم مربوطه',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3005005,
                    'name' => '	كليدها ، سوئيچ ها و تايمر',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3005008,
                    'name' => '	برق فشار قوي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3006001,
                    'name' => '	تجهيزات و قطعات يدكي آزمايشگاه',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3006002,
                    'name' => '	مواد اوليه آزمايشگاه',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3006003,
                    'name' => '	شيشه آلات و وسايل آزمايشگاه',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3007001,
                    'name' => '	روليك ها ، نوار نقاله ها و لوازم مربوطه',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3007004,
                    'name' => '	ريگلاتور',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3007005,
                    'name' => '	استوانه ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3007006,
                    'name' => '	كوبلينگ ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3008001,
                    'name' => '	جرم ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3008002,
                    'name' => '	مواد افزودني ديرگداز',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3008003,
                    'name' => '	قطعات يدکي مکانيکي کوره',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3009001,
                    'name' => '	قطعات يدکي مکانيکي همگن ساز',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3010001,
                    'name' => '	موتور ديزل ژنراتور',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3011002,
                    'name' => '	قطعات يدکي مکانيکي حمام قلع',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3012001,
                    'name' => '	قطعات يدکي مکانيکي لهر',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3012002,
                    'name' => '	قطعات يدکي برق لهر',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3013002,
                    'name' => '	قطعات مکانيکي بچ پلنت',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3014001,
                    'name' => '	قطعات يدکي پمپ خانه و اير کولر',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3015001,
                    'name' => '	قطعات يدکي مکانيکي فرآوري',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3015002,
                    'name' => '	قطعات يدکي فيلترينگ',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3020001,
                    'name' => '	قطعات يدکي نيتروژن',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3021001,
                    'name' => '	قطعات يدکي هيدروژن',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3022001,
                    'name' => '	قطعات يدکي مکانيکي کمپرسور سيار',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3023001,
                    'name' => '	قطعات يدکي دوجداره',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3023002,
                    'name' => '	قطعات يدکي آيينه',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3023003,
                    'name' => '	قطعات يدکي ساتينا',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3023004,
                    'name' => '	قطعات يدکي لمينت',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3023005,
                    'name' => '	قطعات يدکي تمپر',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3024002,
                    'name' => '	تجهيزات آزمايشگاه بلوک سبک',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 3024003,
                    'name' => '	قطعات آجر ماسه آهکي ',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4001002,
                    'name' => '	مصالح ساختماني و بنايي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4001003,
                    'name' => '	تجهيزات عمراني',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4002001,
                    'name' => '	جك ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4002002,
                    'name' => '	حديده و قلاويز',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4002003,
                    'name' => '	انواع گيره',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4002005,
                    'name' => '	انواع تلمبه',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4002006,
                    'name' => '	آچارها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4004001,
                    'name' => '	كولر و بخاري و پنكه و غيرو',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4004002,
                    'name' => '	تجهيزات و ملزومات اداري',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4003001,
                    'name' => '	دستگاه جوش',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4003002,
                    'name' => '	دريل وفرز و ميني فرز و پيكور',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4003003,
                    'name' => '	اره برقي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4003004,
                    'name' => '	پمپ باد',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4003005,
                    'name' => '	دستگاه اتصال لوله',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4003006,
                    'name' => '	تجهيزات تخصصي برق',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4004004,
                    'name' => '	تجهيزات آشپزخانه',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4006001,
                    'name' => '	انواع پرژكتور',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4004003,
                    'name' => '	انواع ترازو',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4004005,
                    'name' => '	نرم افزار',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4005001,
                    'name' => '	انواع پمپ',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4005002,
                    'name' => '	تجهيزات آتشنشاني',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4005003,
                    'name' => '	تجهيزات شوفاژ',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4005004,
                    'name' => '	تجهيزات گاز',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4006002,
                    'name' => '	تاسيسات شبكه',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4006003,
                    'name' => '	تاسيسات برق فشار قوي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4007001,
                    'name' => '	ليفتراك',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4007003,
                    'name' => '	ماشين هاي سنگين',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4007004,
                    'name' => '	ماشين سواري و و انت',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4007007,
                    'name' => '	دوچرخه و لوازم آن',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4008001,
                    'name' => '	زنجير ها و لوازم مربوطه',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4008002,
                    'name' => '	الكتروموتورها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4008003,
                    'name' => '	انواع بالابر',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4008004,
                    'name' => '	ماشين الات مكانيكي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4010001,
                    'name' => '	تجهيزات و قطعات يدكي آزمايشگاه',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4011003,
                    'name' => '	رک دوکاره',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4011001,
                    'name' => '	رک ايساتيس',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4011004,
                    'name' => '	رک جامبو',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4011006,
                    'name' => '	رک فرانسوي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4012001,
                    'name' => '	ماشين آلات  توليدي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4013,
                    'name' => '	ساختمان ها',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 450111,
                    'name' => '	پودر سيليس درجه يک',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 450110,
                    'name' => '	پودر سيليس خشک درجه يک',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 450112,
                    'name' => '	پودر سيليس درجه دو',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 450211,
                    'name' => '	پودر دولوميت درجه يک',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 450311,
                    'name' => '	پودر آهک درجه يک',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 450411,
                    'name' => '	پودر فلدسپات درجه يک',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 450413,
                    'name' => '	پودر فلدسپات درجه سه',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 46060504,
                    'name' => '	بلوک سبک درجه 2 و 3',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 46060511,
                    'name' => '	بلوک سبک درجه 1 فله',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 46060514,
                    'name' => '	بلوک سبک درجه 1 تسمه کش',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 46060518,
                    'name' => '	بلوک سبک درجه 1 شيرينگ حرارتي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 46060512,
                    'name' => '	بلوک سبک درجه 1 استريچر',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 46,
                    'name' => '	انبار هبلکس',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 460,
                    'name' => '	بلوک سبک',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4620100,
                    'name' => '	ملات بلوک سفيد',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4620101,
                    'name' => '	ملات بلوک رنگي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4620201,
                    'name' => '	پلاستر آستر رنگي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4620200,
                    'name' => '	پلاستر آستر سفيد',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4620300,
                    'name' => '	چسب کاشي سفيد',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4620301,
                    'name' => '	چسب کاشي رنگي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4620501,
                    'name' => '	پودر بند کشي رنگي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4620600,
                    'name' => '	گروت صنعتي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4620700,
                    'name' => '	چسب آجر نسوز سفيد',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4620701,
                    'name' => '	چسب آجر نسوز رنگي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4621000,
                    'name' => '	عايق رطوبت',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4620900,
                    'name' => '	ضد حريق',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4620210,
                    'name' => '	پلاستر لايه نهايي سفيد',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4620211,
                    'name' => '	پلاستر لايه نهايي رنگي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4620500,
                    'name' => '	پودر بند کشي سفيد',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4631,
                    'name' => '	بست فلزي',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 4642,
                    'name' => '	ملاقه شيار',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 46600,
                    'name' => '	بلوک سبک کام و زبانه',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 5012035,
                    'name' => '	شيشه سوپرکلير 3.5 ميل',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 5011040,
                    'name' => '	شيشه  4 ميل',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 5012040,
                    'name' => '	شيشه سوپرکلير 4 ميل',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 50009,
                    'name' => '	گروه کالا',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 5012050,
                    'name' => '	شيشه سوپرکلير 5 ميل',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 5012060,
                    'name' => '	شيشه سوپرکلير 6 ميل',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 5012060996,
                    'name' => '	شيشه 6 ميل سوپر جامبو عرض 6',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
                array(
                    'rayvarz_id' => 5012080,
                    'name' => '	شيشه سوپرکلير 8 ميل',
                    'created_at' => now(),
                    'updated_at' => now(),
                ),
            )

        );
    }
}
