<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CenterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('centers')->insert(array(
            // array(
            //     'rayvarz_id' => 1000000,
            //     'name' => 'مراکز هزينه',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1100001,
            //     'name' => '**مراكزهزينه  توليدي خدماتي فلوت',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            array(
                'rayvarz_id' => 1100002,
                'name' => 'واحدهمگن ساز',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100003,
                'name' => 'واحدبچ پلنت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100004,
                'name' => 'واحد کوره ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100005,
                'name' => 'واحدحمام قلع',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100006,
                'name' => 'واحد لهر',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100007,
                'name' => 'واحد کاتينگ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100008,
                'name' => 'واحد بسته بندي فلوت - باکس چوبي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100009,
                'name' => 'دفتر انبارمحصول فلوت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100010,
                'name' => 'واحد هيدروژن',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100011,
                'name' => 'واحد نيتروژن',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100013,
                'name' => 'دفتر توليدفلوت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100014,
                'name' => 'واحد تعمير و نگهداري فلوت - PM',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100015,
                'name' => 'واحد برق فلوت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100016,
                'name' => 'واحد تاسيسات فلوت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100017,
                'name' => 'واحد مديريت کنترل کيفيت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100018,
                'name' => 'واحد مکانيک فلوت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100019,
                'name' => 'واحد آزمايشگاه فيزيک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100020,
                'name' => 'واحد باسکول فلوت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100021,
                'name' => 'واحد کوتينگ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100022,
                'name' => 'واحد بارگيري  فلوت - بارگيري فله',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100023,
                'name' => 'سالن توليد فلوت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100024,
                'name' => 'واحد کپي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100025,
                'name' => 'آزمايشگاه صنعتي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100026,
                'name' => 'واحد بسته بندي فلوت - خرک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100027,
                'name' => 'ايزو',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100028,
                'name' => 'واحد بارگيري فلوت - خرک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100030,
                'name' => 'برق مصرفي فلوت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100031,
                'name' => 'گاز مصرفي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100032,
                'name' => 'واحد CNC خط فلوت ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100033,
                'name' => 'واحد ابزار دقيق',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1100034,
                'name' => 'آب مصرفي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            // array(
            //     'rayvarz_id' => 1101000,
            //     'name' => '**مراكزهزينه  توليدي خدماتي فرآوري',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            array(
                'rayvarz_id' => 1101001,
                'name' => 'واحد سنگ شکن فکي و مخروطي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1101002,
                'name' => 'واحد فيلترينگ و تيکنر (تسويه و سيرکولاسيون)',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1101003,
                'name' => 'واحد آرايش و آبگيري',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1101004,
                'name' => 'واحد پمپ خانه فرآوري',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1101005,
                'name' => 'واحد آهک و دولوميت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1101010,
                'name' => 'واحد تعمير و نگهداري فراوري PM',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1101011,
                'name' => 'واحد تاسيسات فرآوري',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1101012,
                'name' => 'واحد برق فرآوري',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1101013,
                'name' => 'واحد مکانيک فرآوري',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1101014,
                'name' => 'واحد  مديريت فرآوري',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1101015,
                'name' => 'باسکول فرآوري',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1101016,
                'name' => 'آزمايشگاه پايلوت فرآوري',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1101020,
                'name' => 'برق مصرفي فرآوري',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1101021,
                'name' => 'واحد توزيع و فروش فرآوري',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            // array(
            //     'rayvarz_id' => 1101099,
            //     'name' => 'واحد فرآوري ( غير فعال شد )',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1102000,
            //     'name' => '**مراکز هزينه توليدي صنايع جانبي',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            array(
                'rayvarz_id' => 1102001,
                'name' => 'واحد توليد دکوراتيو',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1102002,
                'name' => 'واحد توليد ساتينا',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1102003,
                'name' => 'واحد توليد لمينت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1102004,
                'name' => 'واحد توليد آيينه',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1102005,
                'name' => 'واحد توليد دوجداره',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1102006,
                'name' => 'واحد توليد سکوريت',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1102007,
                'name' => 'واحد CNC  صنايع  جانبي',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1102008,
                'name' => 'واحد تمپر',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1102009,
                'name' => 'واحد لبه زن (Edging)',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1102010,
                'name' => 'واحد دوجداره حرارتي',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1102011,
                'name' => 'واحد پرينتينگ (تکنولوژي هات گلاس)',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1102012,
                'name' => 'واحد توليد شيشه رفلکس',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1102013,
                'name' => 'واحد توزيع و فروش صنايع جانبي',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            // array(
            //     'rayvarz_id' => 1102099,
            //     'name' => '( غير فعال ) واحد آيينه ',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1103000,
            //     'name' => '**مراکز هزينه توليدي بلوک سبک',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            array(
                'rayvarz_id' => 1103001,
                'name' => 'واحد فرآوري مواد اوليه بلوک سبک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1103005,
                'name' => 'واحد بالميل بلوک سبک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1103006,
                'name' => 'واحد اتاق کنترل بلوک سبک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1103007,
                'name' => 'واحد گرم خانه بلوک سبک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1103008,
                'name' => 'واحد برش بلوک سبک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1103009,
                'name' => 'واحد اتوکلاو بلوک سبک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1103010,
                'name' => 'واحد سپريتور بلوک سبک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1103011,
                'name' => 'واحد بسته بندي بلوک سبک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1103012,
                'name' => 'واحد آزمايشگاه بلوک سبک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1103013,
                'name' => 'واحد کنترل کيفيت بلوک سبک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1103014,
                'name' => 'واحد مکانيک بلوک سبک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1103015,
                'name' => 'واحد برق بلوک سبک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1103016,
                'name' => 'واحد تاسيسات بلوک سبک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1103017,
                'name' => 'واحد باسکول بلوک سبک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1103018,
                'name' => 'واحد توزيع و فروش بلوک سبک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1103020,
                'name' => 'واحد مديريت بلوک سبک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1103021,
                'name' => 'ساختمان مدرسه سبز برکت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            // array(
            //     'rayvarz_id' => 1104000,
            //     'name' => '**مراکز هزينه توليدي ملات خشک',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            array(
                'rayvarz_id' => 1104001,
                'name' => 'واحد فرآوري ملات خشک',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1104002,
                'name' => 'واحد دراير ملات خشک',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1104003,
                'name' => 'واحد ميکسر ملات خشک',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1104004,
                'name' => 'واحد سيلو ملات خشک',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1104005,
                'name' => 'واحد بسته بندي ملات خشک',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1104006,
                'name' => 'واحد آزمايشگاه ملات خشک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            // array(
            //     'rayvarz_id' => 1105000,
            //     'name' => '	**مراکز هزينه توليدي آلومينيوم',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            array(
                'rayvarz_id' => 1105001,
                'name' => '	واحد آلومينيوم',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            // array(
            //     'rayvarz_id' => 1106000,
            //     'name' => '	**مراکز هزينه توليدي آجر ماسه آهکي',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            array(
                'rayvarz_id' => 1106001,
                'name' => '	واحد آجر ماسه سيليسي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            // array(
            //     'rayvarz_id' => 1107000,
            //     'name' => '	**مراکز هزينه توليدي فوم سازي',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            array(
                'rayvarz_id' => 1107001,
                'name' => '	واحد فوم سازي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            // array(
            //     'rayvarz_id' => 1199000,
            //     'name' => '	 مشترك توليدي ( غير فعال شد )',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1200000,
            //     'name' => '	**مراكزهزينه هاي خدماتي',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            array(
                'rayvarz_id' => 1200001,
                'name' => '	واحد آزمايشگاه شيمي(مرکزي)',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200002,
                'name' => '	واحد پمپ خانه مرکزي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200003,
                'name' => '	واحد آتش نشاني ',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1200004,
                'name' => '	واحد رستوران (آشپزخانه )',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1200005,
                'name' => '	واحد ساخت و توليد (سازه ها)',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1200006,
                'name' => '	واحد لجستيک ',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1200007,
                'name' => '	واحد انتظامات و دفتر نگهباني  ',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1200008,
                'name' => '	واحد ديزل',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1200009,
                'name' => '	واحد کارگاه نجاري',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1200010,
                'name' => '	واحد تاسيسات سوخت (مخازن سوخت )',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1200011,
                'name' => '	واحد مهندسي معکوس (ماشين سازي)',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1200012,
                'name' => '	واحد معدن',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1200013,
                'name' => '	واحد بهداري',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1200014,
                'name' => '	واحد بچينگ',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1200015,
                'name' => '	واحد عمران',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1200016,
                'name' => '	واحد زيباسازي و خدمات',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1200017,
                'name' => '	واحد دپارتمان توليد',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1200020,
                'name' => '	واحد خدمات و کارپردازي',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1200022,
                'name' => '	واحد جرثقيل ها',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1200024,
                'name' => '	واحد تراکتور',
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'rayvarz_id' => 1200025,
                'name' => '	واحد لودر و بلدوزر و بيل مکانيکي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200026,
                'name' => '	واحد ليفتراک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200027,
                'name' => '	واحد ماشين سنگين ( برون سازماني )',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200028,
                'name' => '	واحد ماشين سبک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200029,
                'name' => '	واحد موتور سيکلت و دوچرخه',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200030,
                'name' => '	واحد ميکسرها',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200031,
                'name' => '	واحد تانکرها',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200032,
                'name' => '	واحد ايمني',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200033,
                'name' => '	واحد طرح و توسعه',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200037,
                'name' => '	واحد تعميرات لجستيک ( تعميرگاه مرکزي)',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200038,
                'name' => '	دفتر مدير کارخانه',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200039,
                'name' => '	واحد اداري کارگزيني',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200040,
                'name' => '	واحد بازرگاني',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200041,
                'name' => '	واحد بازرگاني خارجي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200042,
                'name' => '	مهمانسرا  شهر',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200043,
                'name' => '	مزرعه پتکستان',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200044,
                'name' => '	تعميرگاه مرکزي فلوت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200045,
                'name' => '	واحد دامداري',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200046,
                'name' => '	واحد ماشين سنگين ( درون سازماني )',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200047,
                'name' => '	بانک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200048,
                'name' => '	نانوائي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200049,
                'name' => '	کمپ کارگري',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200050,
                'name' => '	واحد آموزش',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200051,
                'name' => '	مهمانسراي پشت صنايع جانبي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200052,
                'name' => '	معدن متکستانه ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200053,
                'name' => '	معدن غدير ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1200054,
                'name' => '	ايستگاه پست 63برق ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            // array(
            //     'rayvarz_id' => 1202000,
            //     'name' => '	**مراکز هزينه خدماتي صنايع جانبي',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            array(
                'rayvarz_id' => 1202001,
                'name' => '	واحد برق صنايع جانبي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1202002,
                'name' => '	واحد تاسيسات صنايع جانبي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1202003,
                'name' => '	واحد کنترل کيفيت صنايع جانبي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1202004,
                'name' => '	واحد مکانيک صنايع جانبي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1202005,
                'name' => '	واحد آزمايشگاه فيزيک صنايع جانبي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1202006,
                'name' => '	واحد مديريت صنايع جانبي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1202007,
                'name' => '	تعمير و نگهداري - PM صنايع جانبي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1202008,
                'name' => '	دفتر توليد صنايع جانبي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1202009,
                'name' => '	ابزار دقيق صنايع جانبي ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1202010,
                'name' => '	اتاق مانيتورينگ صنايع جانبي ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1299000,
                'name' => '	مركزهزينه هاي مشترك خدماتي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            // array(
            //     'rayvarz_id' => 1300000,
            //     'name' => '	**مراكزهزينه هاي اداري وتشكيلاتي',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            array(
                'rayvarz_id' => 1300001,
                'name' => '	ساختمان اداري و تشكيلاتي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1300002,
                'name' => '	دفتر مدير عامل',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1300003,
                'name' => '	امور حسابداري مالي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1300005,
                'name' => '	دفتر تهران',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1300009,
                'name' => '	واحد آمار و برنامه ريزي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1300010,
                'name' => '	سالن اجتماعات و جلسات',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1300012,
                'name' => '	دفتر امارات',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1300013,
                'name' => '	واحد حقوقي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1300014,
                'name' => '	دفتر عمان',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1300015,
                'name' => '	واحد نمايشگاه صنايع تزيين تکميل',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1300016,
                'name' => '	انبار تهران-غيرفعال شد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1300017,
                'name' => '	واحد انفورماتيک ( it )',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1300018,
                'name' => '	دفتر و انبار قطر',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1300019,
                'name' => '	انبار عمان',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1300020,
                'name' => '	دفتر چين',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1300021,
                'name' => '	دفتر بندرعباس',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1300022,
                'name' => '	باغ مشهد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1300023,
                'name' => '	نمايشگاه بلوک ( ساختمان اداري )',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1300024,
                'name' => '	کميسيون معاملات ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1300025,
                'name' => '	واحد برنامه نويسي ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            // array(
            //     'rayvarz_id' => 1400000,
            //     'name' => '	**مراكزهزينه هاي توزيع وفروش',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            array(
                'rayvarz_id' => 1400001,
                'name' => '	مرکز توزيع وفروش',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1400002,
                'name' => '	فروشگاه حاج محمود (مرکز فروش در شهر )',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1499000,
                'name' => '	مركز هزينه هاي مشترك توزيع و فروش',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            // array(
            //     'rayvarz_id' => 1500000,
            //     'name' => '	Inventory Centers***',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            array(
                'rayvarz_id' => 1500001,
                'name' => '	انبار مواد اوليه مرکزي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500002,
                'name' => '	انبار مواد اوليه صنايع جانبي و شيميايي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500003,
                'name' => '	انبار عمومي و ملزومات ( مرکزي )',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500004,
                'name' => '	انبار رک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500005,
                'name' => '	انبار قطعات',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500006,
                'name' => '	انبار دارايي ثابت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500007,
                'name' => '	انبار فرآوري',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500008,
                'name' => '	انبار محصول فلوت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500009,
                'name' => '	انبار محصول صنايع جانبي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500010,
                'name' => '	انبار در جريان ساخت صنايع جانبي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500011,
                'name' => '	انبار سوخت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500012,
                'name' => '	انبار شيشه بندرعباس',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500013,
                'name' => '	انبار تهران (شورآباد)-غيرفعال شد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500014,
                'name' => '	انبار ضايعات',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500015,
                'name' => '	انبار هبلکس - ملات',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500016,
                'name' => '	انبار هبلکس تهران',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500017,
                'name' => '	انبار آلومينيوم',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500018,
                'name' => '	انبار مازاد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500019,
                'name' => '	انبار هبلکس بندرعباس',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500020,
                'name' => '	انبار مصرفي هبلکس',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500021,
                'name' => '	انبار ملات تهران',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500022,
                'name' => '	انبار اسکله',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500023,
                'name' => '	انبار شلمچه',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500024,
                'name' => '	انبار ماهي رود ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500025,
                'name' => '	انبار لجستيک ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500026,
                'name' => '	انبار نجاري ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1500080,
                'name' => '	انبار محصول کشورهاي همسايه',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1599999,
                'name' => '	بستن افتتاحيه و اختتاميه انبار',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            // array(
            //     'rayvarz_id' => 1600000,
            //     'name' => '	مراکز اماني ***',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            array(
                'rayvarz_id' => 1600001,
                'name' => '	کالاي اماني ما نزد ديگران ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            // array(
            //     'rayvarz_id' => 1800000,
            //     'name' => '	مراکز جهت حسابداري صنعتي **** استفاده نشود  ',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            array(
                'rayvarz_id' => 1800001,
                'name' => '	جهت حسابداري صنعتي( برش)  ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1800002,
                'name' => '	جهت حسابداري صنعتي( برش- فعاليت)  ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1800003,
                'name' => '	جهت حسابداري صنعتي( پروسس) ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1800004,
                'name' => '	جهت حسابداري صنعتي( پروسس- فعاليت)  ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1800005,
                'name' => '	جهت حسابداري صنعتي( دوجداره- فعاليت)  ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1800010,
                'name' => '	مرکز پروسس',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1900000,
                'name' => '	داراييهاي در دست تكميل  ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1900001,
                'name' => '	ساختمان اداري',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            // array(
            //     'rayvarz_id' => 1900002,
            //     'name' => '	(غير فعال) ساختمان توليدي',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900003,
            //     'name' => '	(غير فعال)ساختمان انبار',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900004,
            //     'name' => '	(غير فعال)ساختمان نگهباني',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900005,
            //     'name' => '	(غير فعال)فضاي سبز',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900006,
            //     'name' => '	(غير فعال)حصارکشي',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900007,
            //     'name' => '	(غير فعال)مشترک تاسيسات ',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900008,
            //     'name' => '	(غير فعال)استخراج و فراوري ',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            array(
                'rayvarz_id' => 1900009,
                'name' => '	محوطه سازي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            // array(
            //     'rayvarz_id' => 1900010,
            //     'name' => '	(غير فعال)ماشين آلات ',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900011,
            //     'name' => '	(غيرفعال) تاسيسات سوخت (مخازن سوخت )',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900012,
            //     'name' => '	(غير فعال)معدن دولوميت طبس ',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900013,
            //     'name' => '	(غير فعال)معدن دولوميت ابرکوه',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900014,
            //     'name' => '	(غير فعال)معدن دولوميت چک چک  ',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900015,
            //     'name' => '	(غير فعال)معادن ',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900016,
            //     'name' => '	(غير فعال)معدن سيليس سورك',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900017,
            //     'name' => '	(غير فعال)معدن سيليس و فلدسپات مزرعه نو (چاباشه)',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900018,
            //     'name' => '	(غير فعال)معدن پتكستان',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900019,
            //     'name' => '	(غير فعال)تاسيسات آب ',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900020,
            //     'name' => '	(غير فعال)تاسيسات برق',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900021,
            //     'name' => '	(غير فعال)شاسي تريلي كش وتانكر',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900022,
            //     'name' => '	(غير فعال)پاركينگ',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900023,
            //     'name' => '	(غير فعال)آبرو',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900024,
            //     'name' => '	(غير فعال)اتاق ديزل',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900025,
            //     'name' => '	(غير فعال)سالن توليد آئينه',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900026,
            //     'name' => '	(غير فعال)سالن كوره',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900027,
            //     'name' => '	(غير فعال)سالن حمام قلع',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900028,
            //     'name' => '	(غير فعال)خاكبرداري و تسطيح',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900029,
            //     'name' => '	ا(غير فعال)نبار مركزي',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900030,
            //     'name' => '	(غير فعال)روشنائي محوطه',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900031,
            //     'name' => '	(غير فعال)تانكر هوائي',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900032,
            //     'name' => '	(غير فعال)واحد فني',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900033,
            //     'name' => '	(غير فعال)موتورخانه و تاسيسات',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900034,
            //     'name' => '	(غير فعال)كارگاه آهنگري',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900035,
            //     'name' => '	(غير فعال)سالن هيدروژن',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900036,
            //     'name' => '	(غير فعال)سالن نيتروژن',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900037,
            //     'name' => '	(غير فعال)سالن بچه سوله',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900038,
            //     'name' => '	(غير فعال)حفر چاه عميق',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900039,
            //     'name' => '	(غير فعال)سالن جعبه سازي',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900040,
            //     'name' => '	(غير فعال)استخر آب',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900041,
            //     'name' => '	(غير فعال)سالن لهر و كاتينگ',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900042,
            //     'name' => '	(غير فعال)خيابان كش و جدول گذاري',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900043,
            //     'name' => '	(غير فعال)اگزوز كوره',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900044,
            //     'name' => '	(غير فعال)سالن همگن ساز',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900045,
            //     'name' => '	(غير فعال)اتاق بويلر',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900046,
            //     'name' => '	(غير فعال)بچ پلنت',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900047,
            //     'name' => '	(غير فعال)اتاق كنترل',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900048,
            //     'name' => '	(غير فعال)پياده روسازي',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900049,
            //     'name' => '	(غير فعال)معدن ميدان توت',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900050,
            //     'name' => '	(غير فعال)تاسيسات گاز',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900051,
            //     'name' => '	(غير فعال)تاسيسات هواي فشرده',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900052,
            //     'name' => '	(غير فعال)تاسيسات بخارآب',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900053,
            //     'name' => '	(غير فعال)تاسيسات تانك هاي گازوئيل',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900054,
            //     'name' => '	(غير فعال)تاسيسات حرارتي برودتي',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900055,
            //     'name' => '	(غير فعال)تانكر2000ليتري گالوانيزه',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            // array(
            //     'rayvarz_id' => 1900056,
            //     'name' => '	(غير فعال)معدن ندوشن',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            array(
                'rayvarz_id' => 1900057,
                'name' => '	بلوک سبک و سيليکابرد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1900058,
                'name' => '	ساختمان انبار گمرک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1900059,
                'name' => '	رک در جريان ساخت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1900060,
                'name' => '	سالن ملات خشک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1900061,
                'name' => '	ايستگاه پست برق',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1900062,
                'name' => '	مشترک تاسيسات',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1900063,
                'name' => '	مشترک وسايط نقليه',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1900064,
                'name' => '	مشترک اثاثيه منصوبات',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1900065,
                'name' => '	مشترک نرم افزارهاي مالي ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1900066,
                'name' => '	مشترک معادن ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1900067,
                'name' => '	مشترک ابزارآلات',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1900068,
                'name' => '	مرکز صنايع جانبي ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1900069,
                'name' => '	ساختمان الگوي عمران ( واحد فرآوري )',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1900070,
                'name' => '	کربنات بندر عباس ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 1999000,
                'name' => '	مركز مشترك پروژههاي در دست تكميل ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            // array(
            //     'rayvarz_id' => 1999999,
            //     'name' => '	(غير فعال)مرکز ثابت ',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ),
            array(
                'rayvarz_id' => 11200000,
                'name' => '	دارائيهاي در دست تکميل ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 11202000,
                'name' => '	ساختمانهاي در دست تکميل ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 11202001,
                'name' => '	ساختمان توليد در دست تکميل ',
                'created_at' => now(),
                'updated_at' => now(),
            )

        ));
    }
}
