<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemConsumptionTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('item_consumption_types')->insert(array(
            array(
                'rayvarz_id' => 1,
                'name' => 'جهت فروش',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 2,
                'name' => 'اماني رک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 3,
                'name' => 'جهت توليد / بسته بندي ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 4,
                'name' => 'جهت قواره',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 5,
                'name' => 'جهت تبديلات	',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 6,
                'name' => 'جهت قواره دو جداره',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 7,
                'name' => 'جهت قواره لمينت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 8,
                'name' => 'جهت تمپر	',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 9,
                'name' => 'ضايعات خورده شيشه',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 10,
                'name' => '	جهت تعميرات',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 11,
                'name' => '	انتقال جهت انبارگرداني',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 12,
                'name' => '	جهت تست در کارخانه',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 13,
                'name' => '	نمايشگاه	',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 14,
                'name' => '	بهره برداري	',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21103000,
                'name' => '	* *****تاسيسات*****	',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21199999,
                'name' => '	* ***** اموال ، ماشين آلات و تجهيزات *****	',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72000000,
                'name' => '	* ***** هزينه ها*****	',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72208000,
                'name' => '	رستوران	',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21299999,
                'name' => '	* ***** ساختمانهاي دردست تكميل  *****	',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 29199999,
                'name' => '	* ***** هزينه تاسيس و قبل از بهره برداري *****	',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 14101001,
                'name' => 'مساعده کارکنان',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 14101003,
                'name' => '	جارى كاركنان',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 14102001,
                'name' => 'مواد اماني ما نزد ديگران',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 15010002,
                'name' => 'موجودي انبار مواد اوليه شيميایي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 15060002,
                'name' => '	حواله ورق جهت بست بلوک سبک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 15070001,
                'name' => 'انبار تبديلات',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21103001,
                'name' => '	تاسيسات آب (کد 9 دارايي)',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21103003,
                'name' => '	تاسيسات باد (کد 9 دارايي)',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21103004,
                'name' => '	تاسيسات باسكول (کد 9 دارايي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21103005,
                'name' => '	تاسيسات بي سيم (کد 9 دارايي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21103006,
                'name' => '	تاسيسات گاز (کد 9 دارايي)',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21103007,
                'name' => '	تاسيسات ساخت بتن (کد 9 دارايي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21103012,
                'name' => '	تاسيسات برق (کد 9 دارايي)',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21103020,
                'name' => '	تاسيسات آب(کد 9 دارايي)',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21104000,
                'name' => '	ماشين آلات و تجهيزات (کد 9 دارايي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21104001,
                'name' => '	تجهيزات توليدي (کد 9 دارايي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21105001,
                'name' => '	ابزار آلات و تجهيزات توليدي (کد 9 داراي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21105002,
                'name' => '	ابزار آلات و تجهيزات آزمايشگاهي (کد 9 د',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21105003,
                'name' => '	ابزار آلات و تجهيزات نقشه برداري (کد 9 ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21105004,
                'name' => '	ابزار آلات و تجهيزات آتش نشاني (کد 9 دا',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21105005,
                'name' => '	ابزارآلات وتجهيزات نگهبان',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21107000,
                'name' => '	وسايط نقليه (کد 9 دارايي)',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21108001,
                'name' => '	اثاثيه و منصوبات توليد (کد 9 دارايي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21108002,
                'name' => '	اثاثيه و منصوبات اداري (کد 9 دارايي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21110001,
                'name' => '	واسط دارايي ثابت ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21201001,
                'name' => '	موجودي جنسي انبار رک در جريان ساخ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21202001,
                'name' => '	ساختمان در دست تكميل',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21202002,
                'name' => '	ساختمان اداري در دست تكمي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21202003,
                'name' => '	ساختمان انبار در دست تكمي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21202005,
                'name' => '	ساختمان نگهباني در دست تكمي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21202006,
                'name' => '	محوطه سازي و فضاي سبز در دست تكمي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21202010,
                'name' => '	ساختمان آئينه در دست تکميل',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21202011,
                'name' => '	ساختمان بلوک سبک در دست تکميل',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21202012,
                'name' => '	ساختمان انبار گمرک در دست تکميل',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21202013,
                'name' => '	ساختمان ملات خشک در دست تکمي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21202014,
                'name' => '	ساختمان سيليکابرد در دست تکمي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21202015,
                'name' => '	ساختمان پست برق در دست تکمي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21202016,
                'name' => '	ساختمان معدن متکستانه در دست تکمي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21203000,
                'name' => '	تاسيسات در دست تكميل',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21204000,
                'name' => '	ماشين آلات و تجهيزات دردست تكمي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21205001,
                'name' => '	معادن دردست تكميل استاني',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 21206001,
                'name' => '	 پروژه دردست تكميل ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 29001001,
                'name' => '	هزينه  قبل از بهره برداري',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 32109099,
                'name' => '	ساير بستانكاران ساير اشخاص و شركته',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 61001003,
                'name' => '	فروش مواد غير محصول',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72001100,
                'name' => '	هزينه مواد مستقيم توليد ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72001200,
                'name' => '	هزينه مواد مصرفي غير مستقيم',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72001300,
                'name' => '	هزينه مواد مصرفي آلومينيو',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72001400,
                'name' => '	هزينه مواد اوليه بلوک سبک  و ملات خش',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72003003,
                'name' => '	هزينه هاي تعمير و نگهداري ساختما',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72003004,
                'name' => '	هزينه هاي تعمير و نگهداري تاسيسات',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72003005,
                'name' => '	تعمير و نگهداري ماشين آلات غير توليد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72003006,
                'name' => '	تعمير و نگهداري ماشين آلات توليد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72003015,
                'name' => '	تعمير و نگهداري ابزار آلات و قالبه',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72003016,
                'name' => '	تعمير و نگهداري وسايط نقلي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72003017,
                'name' => '	تعمير و نگهداري اثاثيه و منصوبا',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72003018,
                'name' => '	تعمير و نگهداري و  مواد مصرفي آزمايشگا',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72003019,
                'name' => '	هزينه سوخت کارخانه',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72003020,
                'name' => '	هزينه سوخت وسايط نقليه',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72003025,
                'name' => '	ابزار و لوازم فني مصرفي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72003027,
                'name' => '	هزينه حمل و نقل و پيک',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72003039,
                'name' => '	هزينه هاي فضاي سبز و محوطه ساز',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72004004,
                'name' => '	آبدار خانه و پذيرايي و تزئينا',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72004006,
                'name' => '	پوشاک و ايمني و بهداشت و درما',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72004009,
                'name' => '	رستوران	',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72004012,
                'name' => '	هزينه هاي ورزشي و تفريح',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72004014,
                'name' => '	هزينه ملزومات مالي و ادار',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72602000,
                'name' => '	آگهي و تبليغات',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72606000,
                'name' => '	هزينه هاي بسته بندي محصو',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 72902004,
                'name' => '	هدايا و نذورات',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 81001000,
                'name' => '	فروش ضايعات ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 81005000,
                'name' => '	ضايعات غير عادي توليد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 81008000,
                'name' => '	فروش اقلام راكد (انبار مازاد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 91003002,
                'name' => '	ابزار و تجهيزات اماني ما نزد ديگرا',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'rayvarz_id' => 91003010,
                'name' => '	ابزار و تجهيزات اماني ديگران نزد ما',
                'created_at' => now(),
                'updated_at' => now(),
            )
            ));
    }
}
