<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductPersianFieldsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('product_persian_fields')->insert(array(
            array(
                'english_name' => 'ItemDataId',
                'persian_name' => 'كد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'IsInactive',
                'persian_name' => 'غيرفعال',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'Name',
                'persian_name' => 'عنوان',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'NameEN',
                'persian_name' => 'عنوان لاتين',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'UnitId',
                'persian_name' => 'واحد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'EquivalentItemId',
                'persian_name' => 'كد معادل',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ItemGroupId',
                'persian_name' => 'گروه كالا',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'TechnicalNo',
                'persian_name' => 'شماره فني',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'MapNo',
                'persian_name' => 'شماره نقشه',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'AttachmentId',
                'persian_name' => 'مستندات چند رسانه اي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'IsProduct',
                'persian_name' => 'محصول',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'IsPart',
                'persian_name' => 'قطعه',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'IsTool',
                'persian_name' => 'ابزار',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'IsPacking',
                'persian_name' => 'بسته بندي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'IsLaboratoryEquipment',
                'persian_name' => 'لوازم آزمايشگاهي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'IsShop',
                'persian_name' => 'فروشگاه',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'IsFixedAsset',
                'persian_name' => 'دارايي ثابت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'IsMold',
                'persian_name' => 'قالب',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'IsMaterial',
                'persian_name' => 'مواد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'IsService',
                'persian_name' => 'خدمت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'IsAccessories',
                'persian_name' => 'ملزومات',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'IsConsumable',
                'persian_name' => 'لوازم مصرفي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'IsOldPartRequired',
                'persian_name' => 'داغي‌دار',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'IsStandardRequestProduct',
                'persian_name' => 'محصول درخواست كالاي استاندارد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'IsFeedable',
                'persian_name' => 'قابل تغذيه',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'IsCuttable',
                'persian_name' => 'برش‌دار',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'IsSemiProduct',
                'persian_name' => 'نيم ساخته',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'SupplierId',
                'persian_name' => 'فروشنده اصلي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'CenterId',
                'persian_name' => 'مركز',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'DefaultCenterId',
                'persian_name' => 'مركز پيش فرض',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ItemCode',
                'persian_name' => 'قلم فهرست كالا / خدمت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ItemReceiptTypeId',
                'persian_name' => 'نوع رسيد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ItemConsumptionTypeId',
                'persian_name' => 'نوع مصرف',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ItemMaintenanceId',
                'persian_name' => 'نحوه نگهداري',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ItemImportanceId',
                'persian_name' => 'درجه اهميت',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ItemUseConditionId',
                'persian_name' => 'وضعيت بكارگيري جنس',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ItemProductionStateId',
                'persian_name' => 'وضعيت توليد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ItemTransportationTypeId',
                'persian_name' => 'نحوه حمل',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ItemPackageTypeId',
                'persian_name' => 'نوع بسته بندي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'OrderTypeId',
                'persian_name' => 'روش سفارش',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'DefaultInventoryOrderId',
                'persian_name' => 'سفارش پيش فرض',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'OrderPoint',
                'persian_name' => 'نقطه سفارش',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'OrderSpanTime',
                'persian_name' => 'مدت پوشش سفارش',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'OrderOptimumQty',
                'persian_name' => 'مقدار بهينه سفارش',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'OrderMinimumQty',
                'persian_name' => 'حداقل ميزان سفارش',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'MonthlyConsumeAverage',
                'persian_name' => 'ميانگين مصرف',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ExpireDuration',
                'persian_name' => 'مدت انقضاء',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'OrderWaitDuration',
                'persian_name' => 'مدت سفارش (انتظار دريافت)',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ToolMinuteRate',
                'persian_name' => 'نرخ دقيقه استفاده ابزار',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'SafetyStock',
                'persian_name' => 'ذخيره احتياطي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'BulkUnitId',
                'persian_name' => 'واحد كل انبار',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'BulkToPieceConvertRate',
                'persian_name' => 'ضريب تبديل واحد كل به جزء',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'OrderUnitId',
                'persian_name' => 'واحد مقدار سفارش',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'OrderToInventoryConvertRate',
                'persian_name' => 'ضريب تبديل سفارش به انبار',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'BomUnitId',
                'persian_name' => 'واحد مقدار ساختار محصول',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'BomToInventoryConvertRate',
                'persian_name' => 'ضريب تبديل انبار به ساختار',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'SalesBulkUnitId',
                'persian_name' => 'واحد مقدار كل',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'SalesPieceUnitId',
                'persian_name' => 'واحد مقدار جزء ',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'SalesBulkToPieceConvertRate',
                'persian_name' => 'ضريب تبديل مقدار كل به جزء',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'SalesBulkToInventoryConvertRate',
                'persian_name' => 'ضريب تبديل واحد انبار به فروش',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'SalesPieceToInventoryConvertRate',
                'persian_name' => 'ضريب تبديل واحد فروش به انبار',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'NetWeight',
                'persian_name' => 'وزن خالص',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'GrossWeight',
                'persian_name' => 'وزن ناخالص',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ContainerWeight',
                'persian_name' => 'وزن ظرف',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'WeightUnitId',
                'persian_name' => 'واحد وزن',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'Length',
                'persian_name' => 'طول',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'LengthUnitId',
                'persian_name' => 'واحد طول',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'Width',
                'persian_name' => 'عرض',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'WidthUnitId',
                'persian_name' => 'واحد عرض',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'Height',
                'persian_name' => 'ارتفاع',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'HeightUnitId',
                'persian_name' => 'واحد ارتفاع',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ItemCharacteristic1Id',
                'persian_name' => 'مشخصه كالا 1',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ItemCharacteristic2Id',
                'persian_name' => 'مشخصه كالا 2',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ItemCharacteristic3Id',
                'persian_name' => 'مشخصه كالا 3',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ItemCharacteristic4Id',
                'persian_name' => 'مشخصه كالا 4',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'DefaultActivity3CenterId',
                'persian_name' => 'فعاليت 3 پيش‌فرض',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'TariffNo',
                'persian_name' => 'شماره تعرفه گمركي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ItemNationalCode',
                'persian_name' => 'كد ملي كالا',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ArrivalItemExcessPercent',
                'persian_name' => 'درصد سرك مجاز رسيد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'AllotmentPercent',
                'persian_name' => 'درصد سهم كالا',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'AllotmentAmount',
                'persian_name' => 'في مبلغ سهم كالا',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'LeadTime',
                'persian_name' => 'پيش‌زمان توليد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'PurityDegree',
                'persian_name' => 'درجه خلوص نرم',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'PurityDegreeRate',
                'persian_name' => 'ضريب درجه خلوص نرم',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ShippingMinimumCapacity',
                'persian_name' => 'حداقل ظرفيت حمل',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'DeliveryExcessQty',
                'persian_name' => 'مقدار سرك تحويل',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ProductionPercent',
                'persian_name' => 'درصد توليد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'SalesToDistributionConvertRate',
                'persian_name' => 'ضريب تبديل واحد فروش به توزيع',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'PackingWeigthUnitId',
                'persian_name' => 'واحد وزن بسته بندي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'MRPPurityDegree',
                'persian_name' => 'درجه خلوصMRP',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'Remarks',
                'persian_name' => 'ملاحظات',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'CreationDate',
                'persian_name' => 'تاريخ ايجاد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'LastModifiedDate',
                'persian_name' => 'تاريخ آخرين تغيير',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'EstimationPrice',
                'persian_name' => 'قيمت برآوردي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'CostAccountingTemplateId',
                'persian_name' => 'شناسه نوع شابلن',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'SalesReservedStock',
                'persian_name' => 'موجودي رزرو شده فروش',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'AssetsClassificationId',
                'persian_name' => 'طبقه‌بندي شركتي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'DepreciationMethodId',
                'persian_name' => 'روش استهلاك',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'UsefulLifetime',
                'persian_name' => 'عمر مفيد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'UsefulLifetimeUnitId',
                'persian_name' => 'كد واحد عمر مفيد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'AssetsDescendingDepreciationRate',
                'persian_name' => 'نرخ استهلاك نزولي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ProductionItemTypeId',
                'persian_name' => 'نوع مواد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'ProductionItemGroupId',
                'persian_name' => 'گروه كالا توليد',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'MaxFeed',
                'persian_name' => 'حداکثر تغذيه',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'MinFeed',
                'persian_name' => 'حداقل تغذيه',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'CodingClassificationId',
                'persian_name' => 'دسته بندي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            array(
                'english_name' => 'SeasonalTradePartType',
                'persian_name' => 'نوع كالا خلاصه معاملات فصلي',
                'created_at' => now(),
                'updated_at' => now(),
            ),
        ));
    }
}
