version: "3.7"
services:
    web:
        build: .
        volumes:
            - ./public:/var/www/html
        ports:
            - 80:80   
    db:
        image: mysql
        volumes: 
            - ./database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: docker_database
        ports:
            - 3306:3306
            